Description: 'AWS CloudFormation IAM_Users_Groups_and_Policies Template: The template 
  will create a new user and add to specific IAM Groups. Note: This template 
  also creates an AWSAccessKeyId/AWSSecretKey pair associated with the new user.'
Parameters:
  Password:
    NoEcho: 'false'
    Type: String
    Description: New account password
    MinLength: '8'
    MaxLength: '15'
    ConstraintDescription: the password must be between 8 and 15 characters
  UserName:
    Type: String
    Description: New account username
    MinLength: '3'  
  Groups:
    Type: CommaDelimitedList
    Description: Please enter IAM Groups [basic, cicd, device_farm_access, engineer,
    infrastructure_engineer, shared_resources, webmaster]
Resources:
  User:
    Type: AWS::IAM::User
    Properties: 
      Groups: !Ref Groups
      LoginProfile:
        Password: !Ref 'Password'
      UserName: !Ref 'UserName'
  Keys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'User'
Outputs:
  AccessKey:
    Value: !Ref 'Keys'
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt [Keys, SecretAccessKey]
    Description: AWSSecretAccessKey of new user